username: mahendarbathini34@gmail.com  #linkedin account email
password: mahi1411 # linkedin Account password
phone_number: (123) 456-7890      # google voice mobile number


role_type: ML  # role can be  ML , UI or QA  
profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

positions:
- 1

locations:      # add location you want to apply
- United States


roletype:
- 1 #onsite
- 2 #remote
- 3 #hybrid


salary: 150000
rate: 90



# - # Company names you want to ignore
blacklist:
- Lucid Motors
- Safeway
 
 
# experience_level:
#   - 1 # Entry level
#   - 2 # Associate
#   - 3 # Mid-Senior level
#   - 4 # Director
#   - 5 # Executive
#   - 6 # Internship
  